### ISSUE TITLE
GetFullPath returns a list with the first node wrong and jumps corners and changes input list

### ISSUE THREAD

**Issue by Andrioden** [juhgiyo/EpPathFinding.cs#7] opened 2017-03-12 18:41 UTC
```
BaseGrid searchGrid = new StaticGrid(myWidth, myHeight);

for (int x = 0; x < myWidth; x++)
    for (int z = 0; z < myHeight; z++)
        searchGrid.SetWalkableAt(x, z, true);

var staticlyCachedJpParam = new JumpPointParam(searchGrid, false, false);

GridPos from = new GridPos(61, 73);
GridPos to = new GridPos(67, 98);
staticlyCachedJpParam.Reset(from, to);

List<GridPos> pathTurns = JumpPointFinder.FindPath(staticlyCachedJpParam);
List<GridPos> fullPath = JumpPointFinder.GetFullPath(pathTurns);
```

fullPath now has the following elements (67,79) (62, 74) (63,75) (64,76)... and then etc in "correct order", which has three problems:

1. The first node is wrong
2. It didnt take in consideration iCrossCorner = false
3. It also changes the input list routeFound, which is kinda wierd!

Other than that thanks for the algorithm. : )

**Comment by juhgiyo** [comment] 2017-03-13 01:14
Are you using the latest version?

**Comment by Andrioden** [comment] 2017-03-13 02:50
Yes i was. (Not anymore because of your last commit, but I assume is you addressing problem 3).

**Comment by juhgiyo** [comment] 2017-03-13 03:29
I think problem3 could be a main problem if you ran the FindPath multiple times.

Can you check if the problem is fixed?

**Comment by Andrioden** [comment] 2017-03-16 05:14
Okei, I will download the newest code and try again. Will get back to you.

**Comment by Andrioden** [comment] 2017-03-18 13:54
Testet it @juhgiyo, problem 1 and 3 seems solved. Problem 2 still remains. I have written a workaround for myself, so feel free to consider this feedback and not an issue i need solved. But I can ofcourse retest it if you come with an solution. : )

**Comment by juhgiyo** [comment] 2017-03-18 14:02
Thanks alot for the testing and confirmation. It is good to here that some of the issues are fixed.

I'm not sure what is the issue of second one. The full path has nothing to do with iCrossCorner option. Can you send me an example of the path that makes the issue?

**Comment by Andrioden** [comment] 2017-03-18 15:51
The following code illustrates the problem, but I now realised its FindPath that wrongs the wrong GridPoint coords, crossing corner.

`
int width = 20;
int height = 20;

int fromX = 10;
int fromZ = 10;
int toX = 11;
int toZ = 12;

BaseGrid searchGrid = new StaticGrid(width, height);

for (int x = 0; x < width; x++)
    for (int z = 0; z < height; z++)
        searchGrid.SetWalkableAt(x, z, true);

JumpPointParam jpParam = new JumpPointParam(searchGrid, false, false, false);

GridPos from = new GridPos(fromX, fromZ);
GridPos to = new GridPos(toX, toZ);
jpParam.Reset(from, to);

List<GridPos> routeFound = JumpPointFinder.FindPath(jpParam);
var fullPath = JumpPointFinder.GetFullPath(routeFound);
`

**Comment by juhgiyo** [comment] 2017-03-18 16:03
I don't think in your example, turning off crossing corner plays any role.
No crossing corner avoids crossing diagonal **ONLY** when there is a **unwalkable** neighbor node along with the path.
In your case, every grid is walkable, so turning on/off crossing corner doesn't play any role in there, which means it is not the bug.
I guess I can close the issue then! :)

**Closed by juhgiyo** 2017-03-18 16:03 UTC

**Comment by Andrioden** [comment] 2017-03-18 16:08
Okei, then I missunderstood the API. I thought you could force the algorithm to find a non-diagonally moving path.

Yes I guess you can. : p
